# Generated by Django 5.0.1 on 2024-02-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='street_address',
        ),
    ]
