# Generated by Django 5.0.1 on 2024-03-18 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_remove_checkout_items_checkout_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='items',
            new_name='item',
        ),
    ]
