# Generated by Django 5.0.1 on 2024-03-18 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_unique_together'),
        ('checkout', '0008_paymentoptions_alter_payment_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='item',
        ),
        migrations.AddField(
            model_name='checkout',
            name='items',
            field=models.ManyToManyField(to='cart.cart'),
        ),
        migrations.AddField(
            model_name='paymentoptions',
            name='payment_type',
            field=models.CharField(choices=[('credit card', 'Credit Card'), ('debit card', 'Debit Card'), ('paypal', 'Paypal'), ('cash on delivery', 'Cash On Delivery'), ('bank transfer', 'Bank Transfer'), ('bitcoin', 'Bitcoin'), ('other', 'Other')], default='other', max_length=255),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.payment'),
        ),
    ]
