# Generated by Django 5.0.1 on 2024-03-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_remove_payment_payment_method_remove_payment_user_and_more'),
    ]

    operations = [
    ]
