# Generated by Django 5.0.1 on 2024-03-20 18:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=99.99, max_digits=10)),
                ('discountPercentage', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('deleted', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('brand', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('thumbnail', models.URLField(blank=True, max_length=500, null=True)),
                ('color', models.CharField(blank=True, choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Black', 'Black'), ('White', 'White')], max_length=120, null=True)),
                ('size', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], max_length=120, null=True)),
                ('images', models.ManyToManyField(blank=True, to='product.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
