# Generated by Django 5.0.1 on 2024-02-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountPercentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
