# Generated by Django 5.0.1 on 2024-03-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AddField(
            model_name='image',
            name='uid',
            field=models.BigIntegerField(auto_created=True, default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
