# Generated by Django 5.0.1 on 2024-02-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_image_id_alter_image_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail_url',
            new_name='thumbnail',
        ),
    ]
