# Generated by Django 5.0.1 on 2024-03-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_thumbnail_url_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
