# Generated by Django 5.0.1 on 2024-03-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('checkedout', 'Checkedout'), ('cancelled', 'Cancelled')], default='pending', max_length=255),
        ),
    ]
