# Generated by Django 5.0.1 on 2024-03-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('checkedout', 'Checkedout'), ('cancelled', 'Cancelled'), ('shipped', 'Shippes'), ('delivered', 'Delivered')], default='pending', max_length=255),
        ),
    ]
