# Generated by Django 5.0.1 on 2024-03-18 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_status'),
    ]

    operations = [
    ]
